
### Register New hub
POST http://localhost:3000/api/v1/hub/register
Content-Type: application/json

{
    "name":"hub4",
    "password": "hub4"
}

### Login to hub 6048c20ead043f1880f84fc0
POST http://localhost:3000/api/v1/hub/login
Content-Type: application/json

{
    "name":"hub3",
    "password": "hub3"
}

### Connect
POST http://localhost:3000/api/v1/hub/connect
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.1eyJpZCI6IjYwNGEyNDJjNTc2YmRiNDNlNGEyNzBiYSIsImlhdCI6MTYxNTQ4NDU5NiwiZXhwIjoxNjE1NDg0NjExLCJpc3MiOiJlYXN5LWlvdC1zZXJ2ZXIifQ.PxlIL0_fQMPaKRrMfBTyC-f45gpmAdaSjB12JEhcM8qKA
Content-Type: application/json

{
    "name":"hub3",
    "password": "hub3"
}

### UPDATE DEVICE
PUT http://localhost:3000/api/v1/hub/update/6048becc877212168c9b3d38
Content-Type: application/json

{
    "connStatus":"ONLINE"
}

### READ ALL DEVICE 
GET http://localhost:3000/api/v1/hub/read
Content-Type: application/json

### READ SPECIFIC DEVICE by name
GET http://localhost:3000/api/v1/hub/read/JS HUb 3
Content-Type: application/json


### DELETE DEVICE by ID
DELETE   http://localhost:3000/api/v1/hub/delete
Content-Type: application/json

{
    "_id":"6048bf09877212168c9b3d39"
}